apiVersion: v1
kind: Service
metadata:
  name: geoff-wls
  labels:
    run: geoff-wls
spec:
  type: NodePort
  ports:
  - port: 7001
    nodePort: 31000
    protocol: TCP
  selector:
    run: geoff-wls
